### ISSUE TITLE
jshint on CI

### ISSUE THREAD

**Issue by hectorv** [pre-commit/mirrors-jshint#4]
Similar to https://github.com/pre-commit/pre-commit-hooks/issues/265, we started seeing some failures on CI that we had not seen before. Here's the traceback:

```
An unexpected error has occurred: OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pre_commit/error_handler.py", line 47, in error_handler
    yield
  File "/usr/local/lib/python2.7/site-packages/pre_commit/main.py", line 259, in main
    return run(runner, args)
  File "/usr/local/lib/python2.7/site-packages/pre_commit/commands/run.py", line 268, in run
    repo.require_installed()
  File "/usr/local/lib/python2.7/site-packages/pre_commit/repository.py", line 202, in require_installed
    _install_all(self._venvs, self.repo_config['repo'], self.store)
  File "/usr/local/lib/python2.7/site-packages/pre_commit/repository.py", line 102, in _install_all
    language.install_environment(prefix, version, deps)
  File "/usr/local/lib/python2.7/site-packages/pre_commit/languages/node.py", line 66, in install_environment
    ('npm', 'install', '-g', '.') + additional_dependencies,
  File "/usr/local/lib/python2.7/site-packages/pre_commit/languages/helpers.py", line 9, in run_setup_cmd
    cmd_output(*cmd, cwd=prefix.prefix_dir, encoding=None)
  File "/usr/local/lib/python2.7/site-packages/pre_commit/util.py", line 178, in cmd_output
    proc = __popen(cmd, **popen_kwargs)
  File "/usr/local/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

that I got from `/root/.cache/pre-commit/pre-commit.log`:

```
❯ docker run --rm --volume "$(pwd):/code" "$IMAGE_HASH" sh -c "apk add --no-cache git nodejs nodejs-npm && pre-commit run --verbose --files jenkins-build.sh"
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/10) Installing libcurl (7.58.0-r0)
(2/10) Installing pcre2 (10.30-r0)
(3/10) Installing git (2.15.0-r1)
(4/10) Installing nodejs-npm (8.9.3-r0)
(5/10) Installing c-ares (1.13.0-r0)
(6/10) Installing libcrypto1.0 (1.0.2n-r0)
(7/10) Installing http-parser (2.7.1-r1)
(8/10) Installing libssl1.0 (1.0.2n-r0)
(9/10) Installing libuv (1.17.0-r0)
(10/10) Installing nodejs (8.9.3-r0)
Executing busybox-1.27.2-r7.trigger
OK: 107 MiB in 52 packages
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for git://github.com/pre-commit/mirrors-jshint.
[INFO] Initializing environment for git://github.com/pre-commit/mirrors-yapf.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for git://github.com/pre-commit/mirrors-yapf.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for git://github.com/pre-commit/mirrors-jshint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: OSError: [Errno 2] No such file or directory
Check the log at /root/.cache/pre-commit/pre-commit.log
```

This docker image is base on `python:2.7.14-alpine3.7`. Note that I only started installing `nodejs` and `nodjs-npm` (using `apk add`) after I noticed this line in the error log:
```
('npm', 'install', '-g', '.') + additional_dependencies,
```

I thought that the error was because `node/npm` were not installed, but that doesn't seem to be the case. Here's a quick check that `npm` installs correctly:
```
❯ docker run --rm --volume "$(pwd):/code" "$IMAGE_HASH" sh -c "apk add --no-cache git nodejs nodejs-npm && npm --version"
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/10) Installing libcurl (7.58.0-r0)
(2/10) Installing pcre2 (10.30-r0)
(3/10) Installing git (2.15.0-r1)
(4/10) Installing nodejs-npm (8.9.3-r0)
(5/10) Installing c-ares (1.13.0-r0)
(6/10) Installing libcrypto1.0 (1.0.2n-r0)
(7/10) Installing http-parser (2.7.1-r1)
(8/10) Installing libssl1.0 (1.0.2n-r0)
(9/10) Installing libuv (1.17.0-r0)
(10/10) Installing nodejs (8.9.3-r0)
Executing busybox-1.27.2-r7.trigger
OK: 107 MiB in 52 packages
5.5.1
```

And finally, the error goes away after removing this section from our `.pre-commit-config.yaml`:
```
-   repo: git://github.com/pre-commit/mirrors-jshint
    sha: v2.9.5
    hooks:
    -   id: jshint
```

Any suggestions?
Thanks!

**Comment by asottile** [comment]
I'm able to reproduce this -- and actually I'm able to reproduce the error without involving pre-commit (but only while using alpine).

This seems to be a minimal reproduction:

```bash
nodeenv nenv
. nenv/bin/activate
which node
node
```

output:

```console
/tmp/code # nodeenv nenv
 * Install prebuilt node (9.5.0) ..... done.
/tmp/code # . nenv/bin/activate 
(nenv)/tmp/code # which node
/tmp/code/nenv/bin/node
(nenv)/tmp/code # node
bash: /tmp/code/nenv/bin/node: No such file or directory
```

The strange thing is the file _is_ there, and it _is_ executable.

My guess is a libc vs. muslc difference?  You may find better mileage using a more conventional base image (debian? ubuntu? fedora?)

**Comment by hectorv** [comment]
Thanks for the quick response @asottile !
Unfortunately we're pretty much married to Alpine, so I'll keep hacking at it, maybe I'll find a workaround.

**Comment by asottile** [comment]
I have some ideas, though they're going to be hard to incorporate.

If we build node from source it should work fine.

To do that you'll need:

```bash
apk --no-cache add gcc g++ make linux-headers
nodeenv nenv --source  # wait for an eternity
```

I'm trying this now

**Comment by asottile** [comment]
I've opened https://github.com/ekalinin/nodeenv/issues/204 btw

**Comment by asottile** [comment]
Can confirm that after waiting ~30 minutes for node to build from source, the resulting binaries are functional:

```console
...
installing /nenv/include/node/zconf.h
installing /nenv/include/node/zlib.h
 done.
/ # . nenv/bin/activate 
(nenv)/ # node --version
v9.5.0
```

**Comment by asottile** [comment]
A workaround could be to use `local` hooks with `language: system` and globally install `jshint` -- though this kind of defeats one of the [main goals of pre-commit](https://pre-commit.com/#intro) in the first place.

Something like:

```
apk --no-cache add npm
npm install jshint@...
```

and

```yaml
-   repo: local
    hooks:
    -   id: jshint
        name: jshint
        entry: jshint
        language: system
        types: [javascript]
```

**note: above configuration is not tested -- mileage may vary**

**Comment by hectorv** [comment]
In the meantime I tried using `libc6-compat` and got a bit more info that essentially points in the same direction:

```
❯ docker run --rm --volume "$(pwd):/code" "$IMAGE_HASH" sh -c 'apk add --no-cache git libc6-compat nodejs && git --version && npm --version && which npm && pre-commit run --files jenkins-build.sh'

fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/11) Installing libcurl (7.58.0-r0)
(2/11) Installing pcre2 (10.30-r0)
(3/11) Installing git (2.15.0-r1)
(4/11) Installing libc6-compat (1.1.18-r3)
(5/11) Installing nodejs-npm (8.9.3-r0)
(6/11) Installing c-ares (1.13.0-r0)
(7/11) Installing libcrypto1.0 (1.0.2n-r0)
(8/11) Installing http-parser (2.7.1-r1)
(9/11) Installing libssl1.0 (1.0.2n-r0)
(10/11) Installing libuv (1.17.0-r0)
(11/11) Installing nodejs (8.9.3-r0)
Executing busybox-1.27.2-r7.trigger
OK: 107 MiB in 53 packages
git version 2.15.0
5.5.1
/usr/bin/npm
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for git://github.com/pre-commit/mirrors-jshint.
[INFO] Initializing environment for git://github.com/pre-commit/mirrors-yapf.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for git://github.com/pre-commit/mirrors-jshint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: Command: (u'/root/.cache/pre-commit/repohwxjR3/node_env-default/bin/node', u'/root/.cache/pre-commit/repohwxjR3/node_env-default/bin/npm', 'install', '-g', '.', 'jshint@2.9.5')
Return code: 127
Expected return code: 0
Output: (none)
Errors:
    Error relocating /root/.cache/pre-commit/repohwxjR3/node_env-default/bin/node: __register_atfork: symbol not found
    Error relocating /root/.cache/pre-commit/repohwxjR3/node_env-default/bin/node: backtrace: symbol not found


Check the log at /root/.cache/pre-commit/pre-commit.log
```

**Comment by asottile** [comment]
Oh yes! Your other comment reminded me: you can just use `language_version: system`!

**Comment by asottile** [comment]
Not sure there's much more that can be done from the pre-commit side, I've gotten the ball rolling upstream and this appears to be a workaround:

```dockerfile
FROM python:3-alpine
RUN apk add --no-cache bash git nodejs
RUN pip install pre-commit
ADD . /repo
RUN git init /repo && git -C /repo add :/
```

```yaml
repos:
-   repo: https://github.com/pre-commit/mirrors-jshint
    rev: v2.9.5
    hooks:
    -   id: jshint
        language_version: system
```

```console
$ docker build -t test .
...
$ docker run --workdir /repo -ti test pre-commit run --all-files
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-jshint.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-jshint:jshint@2.9.5.
[INFO] Installing environment for https://github.com/pre-commit/mirrors-jshint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
jshint...................................................................Passed
```

The trick here is to _system_ install `nodejs` and then tell `nodeenv` to piggyback on that (via `language_version: system`).
